hard-patch-deluxe-combat: true
container-name-override: true # Disable this if you only want the DeluxeCombat patch, this option could potentially break other plugins if set to true, but will fix any potential future exploits.
exempt:
  equals: []
  contains: []
  startsWith: []