name: ContainerExploitPrevention
version: 1.0
description: Prevents future exploits of using container titles. (like Vulcan 2.8.3)
main: world.minecraftservers.plugin.ContainerExploitPrevention
softdepend:
  - ProtocolLib